apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-server
  annotations:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
  - hosts:
    - workflows.apps.argoproj.io
    secretName: argo-workflows-secret
  rules:
  - host: workflows.apps.argoproj.io
    http:
      paths:
      - path: /
        backend:
          serviceName: argo-server
          servicePort: 2746
