apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: coinflip
spec:
  schedule: '*/5 * * * *'
  serviceAccountName: workflow
  workflowSpec:
    workflowTemplateRef:
      name: coinflip