apiVersion: v1
data:
  # https://github.com/settings/applications/1416526
  config: |
    artifactRepository:
      s3:
        bucket: my-bucket
        keyPrefix: prefix/in/bucket     #optional
        endpoint: 104.155.140.57:9000        #AWS => s3.amazonaws.com; GCS => storage.googleapis.com
        insecure: true                  #omit for S3/GCS. Needed when minio runs without TLS
        accessKeySecret:                #omit if accessing via AWS IAM
          name: argo-artifacts-minio
          key: accesskey
        secretKeySecret:                #omit if accessing via AWS IAM
          name: argo-artifacts-minio
          key: secretkey
    sso:
      issuer: https://dex.apps.argoproj.io/dex
      clientId:
        name: argo-server-sso
        key: clientID
      clientSecret:
        name: argo-server-sso
        key: clientSecret
      redirectUrl: https://workflows.apps.argoproj.io/oauth2/callback
      scopes:
       - groups
      rbac:
        enabled: true
    containerRuntimeExecutor: pns
    workflowDefaults:
      spec:
        activeDeadlineSeconds: 30
        ttlStrategy:
          secondsAfterCompletion: 600
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
