apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-cd-notifications-bot-ingress.yaml
- argo-cd-notifications-bot-certificate.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/master/manifests/install-bot.yaml

patchesStrategicMerge:
- overlays/argocd-notifications-controller-deploy.yaml
- overlays/argocd-notifications-cm.yaml
- overlays/argocd-notifications-bot-service.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/master/catalog/install.yaml

images:
- name: argoprojlabs/argocd-notifications
  newName: ghcr.io/argoproj-labs/argocd-notifications
  newTag: 1.0.0-1e6889d8